version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  target-branch: master
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
    - "giantswarm/team-ludacris"
  ignore:
  - dependency-name: k8s.io/**
    versions:
    - ">=0.17.0"
