---
Installation:
  V1:
    Secret:
      Registry:
        PullSecret:
          DockerConfigJSON: "Dummy Secret"
    GiantSwarm:
      KVMOperator:
        CRD:
          LabelSelector: ""
    Provider:
      KVM:
        DNS:
          Servers: ""
        NTP:
          Servers: ""
    Guest:
      Kubernetes:
        API:
          Auth:
            Provider:
              OIDC:
                ClientID: ""
                IssuerURL: ""
                UsernameClaim: ""
                GroupsClaim: ""
      SSH:
        SSOPublicKey: ""
      Update:
        Enabled: ""
