apiVersion: v1
name: kvm-operator
home: https://github.com/giantswarm/kvm-operator
description: Handles Kubernetes clusters running on a Kubernetes cluster with workers and masters in KVMs on bare metal
version: "[[ .Version ]]"
appVersion: "[[ .AppVersion ]]"
annotations:
  application.giantswarm.io/team: "rocket"
  config.giantswarm.io/version: 1.x.x
